### PR TITLE
Make SSL_CERT_FILE path OS agnostic

### PR DESCRIPTION
**Pull request by pschulze**
Uses `os.path.join` to build a path for SSL_CERT_FILE instead of having it hardcoded. This should allow the app to work with splunk running on windows.

### CODE REVIEW

**Comment by pschulze** [comment]
Also references SPLUNK_HOME so should fix the problem in #12

**Review by samsonnguyen — DISMISSED** [review]

**Review by samsonnguyen — COMMENTED** [review]
Need a version bump

**Review by samsonnguyen — APPROVED** [review]
+1

**Comment by pschulze** [comment]
Fixes #26

**Pull request merged**
